# libraries.conf - Nox package manifest

installed=physics,core

pkg:physics:url=https://github.com/MJDaws0n/novus-physics
pkg:physics:version=0.0.0
pkg:physics:branch=master
pkg:physics:commit=0ca3c45
pkg:physics:min=*
pkg:physics:max=*

pkg:core:url=https://github.com/MJDaws0n/novus-core
pkg:core:version=0.0.0
pkg:core:branch=master
pkg:core:commit=3c01daa
pkg:core:min=*
pkg:core:max=*
